apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: modules.cyclops.com
spec:
  group: cyclops.com
  names:
    plural: modules
    singular: module
    kind: Module
    shortNames:
      - cm
  scope: Namespaced
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                template:
                  type: object
                  properties:
                    name:
                      type: string
                    version:
                      type: string
                values:
                  type: array
                  items:
                    type: object
                    properties:
                      name:
                        type: string
                      value:
                        type: string
            status:
              properties:
                resources:
                  items:
                    properties:
                      group:
                        type: string
                      version:
                        type: string
                      kind:
                        type: string
                      namespace:
                        type: string
                      name:
                        type: string
                      status:
                        type: string
                      health:
                        type: string
                    type: object
                  type: array
                conditions:
                  items:
                    properties:
                      lastTransitionTime:
                        format: date-time
                        type: string
                      message:
                        type: string
                      reason:
                        type: string
                      status:
                        type: string
                      type:
                        type: string
                    required:
                      - message
                      - reason
                      - status
                      - type
                    type: object
                  type: array
              type: object