apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: modules.cyclops.com
spec:
  group: cyclops.com
  names:
    plural: modules
    singular: module
    kind: Module
    shortNames:
      - cm
  scope: Cluster
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                version:
                  type: string
                namespaces:
                  type: array
                  items:
                    type: object
                    properties:
                      name:
                        type: string
                      components:
                        type: array
                        items:
                          type: object
                          properties:
                            kind:
                              type: string
                              enum:
                                - deployment
                                - statfulset
                                - ingress
                                - service
                                - daemonset
                            name:
                              type: string
                          required: [ "kind", "name" ]
                    required: ["name", "components"]
              required: ["version", "namespaces"]
          required: ["spec"]
