apiVersion: apps/v1
kind: Deployment
metadata:
  name: cyclops-ctrl
  namespace: kube-system
  labels:
    app: cyclops-ctrl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cyclops-ctrl
  template:
    metadata:
      labels:
        app: cyclops-ctrl
    spec:
      containers:
        - name: cyclops-ctrl
          image: petarcvit223/cyclops-ctrl:v0.42.0
          ports:
            - containerPort: 8080
          env:
            - name: PORT
              value: "8080"
        - name: mongo
          image: mongo:5.0.0
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              value: username
            - name: MONGO_INITDB_ROOT_PASSWORD
              value: password
---
apiVersion: v1
kind: Service
metadata:
  name: cyclops-ctrl
  namespace: kube-system
  labels:
    app: cyclops-ctrl
spec:
  type: ClusterIP
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: cyclops-ctrl
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cyclops-ui
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cyclops-ui
  template:
    metadata:
      labels:
        app: cyclops-ui
    spec:
      containers:
        - name: cyclops-ui
          image: petarcvit223/cyclops-ui:v0.5.0
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          env:
            - name: REACT_APP_CYCLOPS_CTRL_HOST
              value: http://localhost:8080
      restartPolicy: Always
---
kind: Service
apiVersion: v1
metadata:
  name: cyclops-ui
  namespace: kube-system
spec:
  type: ClusterIP
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
  selector:
    app: cyclops-ui
