apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-web-app
  namespace: my-team
spec:
  selector:
    matchLabels:
      app: my-web-app
  replicas: 3
  template:
    metadata:
      labels:
        app: my-web-app
    spec:
      containers:
      - name: my-web-app
        image: my-docker-registry/my-web-app:v1.2.3
        resources:
          requests:
            memory: "32Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: appname-service
spec:
  type: ClusterIP
  selector:
    app: appname
  ports:
  - port: 3000
    targetPort: 8080
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: traffic-router
spec:
  rules:
    - http:
        paths:
          - path: /
            backend:
              serviceName: servicename
              servicePort: 8080

