name: Controller tests

on:
  push:
    paths:
      - 'cyclops-ctrl/**' # Define the folder path here

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run go test on folder change
        run: |
          cd ${{ github.workspace }}/cyclops-ctrl
          make unit-test
