name: Controller tests

on:
  push:
    paths:
      - 'cyclops-ctrl/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Unit tests
        run: |
          cd ${{ github.workspace }}/cyclops-ctrl
          make unit-test
