name: Deploy lending page to GitHub Pages

on:
  push:
    branches:
      - main
      - landing

permissions:
  contents: write

jobs:
  deploy:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
#      - uses: actions/setup-node@v3
#        with:
#          node-version: 18
#          cache: npm

      - name: Install dependencies and build
        run: |
          cd web
          npm ci
          npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.PERSONAL_TOKEN }}
#          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./web/build
          external_repository: cyclops-ui/cyclops-ui.github.io
          cname: cyclops-ui.com
